/**
 * AUTO-GENERATED by scripts/generate_audio.js
 * Do NOT edit by hand — re-run generate_audio.js to update.
 * Generated: 2026-05-27T03:15:21.197Z
 */
const audioMap = {
  "Have you ever noticed? A coin is round. A clock is round. The sun is round! What shape do they all share?": "/assets/audio/audio_have_you_ever_noticed_a_coin_is_round_a_clock_is_r_0.mp3",
  "Let's find out together!": "/assets/audio/audio_lets_find_out_together_1.mp3",
  "One bright morning, John and Sarah set off on a secret mission to the bustling food court! Their target? The most perfect shape in the universe!": "/assets/audio/audio_one_bright_morning_john_and_sarah_set_off_on_a_sec_2.mp3",
  "The friendly cook handed them a mountain of noodles on a giant, gleaming plate. Look! gasped John. The plate has no corners... it's a circle!": "/assets/audio/audio_the_friendly_cook_handed_them_a_mountain_of_noodle_3.mp3",
  "Wait, look at my lucky gold coin! Sarah cheered, holding it up to the light. It's perfectly round, just like your plate. Another circle!": "/assets/audio/audio_wait_look_at_my_lucky_gold_coin_sarah_cheered_hold_4.mp3",
  "Suddenly, a cool breeze blew over them. They looked up to see a giant ceiling fan spinning super fast. Woosh! The spinning blades make a giant circle! they shouted together.": "/assets/audio/audio_suddenly_a_cool_breeze_blew_over_them_they_looked__5.mp3",
  "They discovered the secret: A circle is a continuous, curved line with ZERO sharp corners! It is perfectly smooth and round.": "/assets/audio/audio_they_discovered_the_secret_a_circle_is_a_continuou_6.mp3",
  "Can you spell the magical shape they found? C. I. R. C. L. E. Circle!": "/assets/audio/audio_can_you_spell_the_magical_shape_they_found_c_i_r_c_7.mp3",
  "Great job! Now let's explore circles ourselves!": "/assets/audio/audio_great_job_now_lets_explore_circles_ourselves_8.mp3",
  "Trace the dotted circle with your finger! Keep it smooth and round!": "/assets/audio/audio_trace_the_dotted_circle_with_your_finger_keep_it_s_9.mp3",
  "You drew a perfect circle! Round and smooth — no corners at all!": "/assets/audio/audio_you_drew_a_perfect_circle_round_and_smooth_no_corn_10.mp3",
  "Almost! A circle has no sharp turns. Try again — nice and smooth!": "/assets/audio/audio_almost_a_circle_has_no_sharp_turns_try_again_nice__11.mp3",
  "Sort the shapes! Does it belong in the Circle bin or the Not a Circle bin?": "/assets/audio/audio_sort_the_shapes_does_it_belong_in_the_circle_bin_o_12.mp3",
  "That's right! A circle is perfectly round with no corners!": "/assets/audio/audio_thats_right_a_circle_is_perfectly_round_with_no_co_13.mp3",
  "Look carefully — does this shape have corners? Circles have none!": "/assets/audio/audio_look_carefully_does_this_shape_have_corners_circle_14.mp3",
  "Is an oval a circle? No! An oval is stretched out. A circle is perfectly round.": "/assets/audio/audio_is_an_oval_a_circle_no_an_oval_is_stretched_out_a__15.mp3",
  "Find all the circles hiding in this picture! Tap each one you see!": "/assets/audio/audio_find_all_the_circles_hiding_in_this_picture_tap_ea_16.mp3",
  "You found a circle! Great spotting!": "/assets/audio/audio_you_found_a_circle_great_spotting_17.mp3",
  "That one has corners! Look for the perfectly round shapes!": "/assets/audio/audio_that_one_has_corners_look_for_the_perfectly_round__18.mp3",
  "Amazing! You found all the circles! You are a Circle Champion!": "/assets/audio/audio_amazing_you_found_all_the_circles_you_are_a_circle_19.mp3",
  "Wow — you explored circles today! Can you name three circles you see at home?": "/assets/audio/audio_wow_you_explored_circles_today_can_you_name_three__20.mp3",
  "Lesson complete! You are a true Circle Explorer! Well done!": "/assets/audio/audio_lesson_complete_you_are_a_true_circle_explorer_wel_21.mp3",
  "Fantastic! That's a circle!": "/assets/audio/audio_fantastic_thats_a_circle_22.mp3",
  "Brilliant! You got it!": "/assets/audio/audio_brilliant_you_got_it_23.mp3",
  "Amazing! Circles have no corners and you know it!": "/assets/audio/audio_amazing_circles_have_no_corners_and_you_know_it_24.mp3",
  "Well done! Keep going!": "/assets/audio/audio_well_done_keep_going_25.mp3",
  "Let's look again! Remember — circles have no corners.": "/assets/audio/audio_lets_look_again_remember_circles_have_no_corners_26.mp3",
  "Almost! Check if the shape is perfectly round.": "/assets/audio/audio_almost_check_if_the_shape_is_perfectly_round_27.mp3",
  "Not quite! A circle has one curved side and zero corners.": "/assets/audio/audio_not_quite_a_circle_has_one_curved_side_and_zero_co_28.mp3",
  "Hint! A circle is perfectly round — no corners, no flat sides.": "/assets/audio/audio_hint_a_circle_is_perfectly_round_no_corners_no_fla_29.mp3",
  "Hint! Count the corners. Circles have zero corners!": "/assets/audio/audio_hint_count_the_corners_circles_have_zero_corners_30.mp3"
};

export default audioMap;
