/**
 * AUTO-GENERATED by scripts/generate_audio.js
 * Maps exact text strings to pre-generated .mp3 file paths.
 * Do NOT edit by hand — re-run generate_audio.js to update.
 *
 * When no pre-generated files exist yet, this map is empty.
 * The audio engine will fall back to dynamic ElevenLabs API calls
 * when VITE_ELEVENLABS_API_KEY is set, or silently skip narration.
 */
const audioMap = {};

export default audioMap;
